--- Makefile.bak	2025-03-29 13:10:18
+++ Makefile	2025-03-28 22:19:06
@@ -191,6 +191,7 @@
 	tcp/tcp.o tcp/tcp-sink.o tcp/tcp-reno.o \
 	tcp/tcp-newreno.o \
 	tcp/tcp-vegas.o tcp/tcp-rbp.o tcp/tcp-full.o tcp/rq.o \
+	tcp/elastic-tcp.o \
 	baytcp/tcp-full-bay.o baytcp/ftpc.o baytcp/ftps.o \
 	tcp/scoreboard.o tcp/scoreboard-rq.o tcp/tcp-sack1.o tcp/tcp-fack.o \
 	tcp/scoreboard1.o tcp/tcp-linux.o tcp/linux/ns-linux-util.o \
